### ISSUE TITLE
[Yenepoya][Support] Issue with data relationship and gender

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#107]
ticket - 
https://avni.freshdesk.com/a/tickets/1153

https://avni.freshdesk.com/a/tickets/1152

Product Bug:-
The app is failing when two identical relations are present even if one of them is voided. 
example:- father-son, son-father

Fix:- We have added one condition in the code, which will not consider voided relations.

Best practices for implementers:-
@nupoorkhandelwal please don't add reverse relation in the relationships.
example:- if we have added Father-son then we should not add the Son-Father relation.

**Comment by sachsk** [comment]
req. is not clear
