### ISSUE TITLE
[Yenepoya][Support] Change in child program

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#112]
**Form** - "Child enrolment" and "Child Growth and Health status Followup"

**ticket -** https://avni.freshdesk.com/a/tickets/1209
1. Add a question - "Is the child exclusively breastfed?" (this should be ask for all children)
2. Question - "Duration of Exclusive breastfeeding in months." change the logic - this should be visible only if the age of the child is greater than 6 months.
3. Question - "Child weaned at 6 months of age." change the logic - this should be visible only if the age of the child is greater than 6 months.

**ticket** - https://avni.freshdesk.com/a/tickets/1210
4. Question - "Present Mid Arm Circumference in cm", ask this question after 1 year of age.

**Comment by sachsk** [comment]
Changes are on uat

**Comment by garimadosar5** [comment]
QA Notes - 
- Point 2 and 3- Logic is not working.
