### ISSUE TITLE
[Yenepoya] Reports to ETL (Urgent)

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/yenepoya#137]
Ticket reference:
https://avni.freshdesk.com/a/tickets/2471

**Reports mentioned in the ticket have to be picked on priority for ETL migration.**

Reports to ETL reference sheet:
https://docs.google.com/spreadsheets/d/15U3mOkcVjHhXlr318uj8DRQNzC6mBOTf-GEPf9SLfTM/edit#gid=693027088

**Comment by Dinesh2019** [comment]
Blocked for testing due to old report for Yenepoya showing below error in jasper 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/7feb290f-bd81-4e67-a03a-6f02536a0c63)

**Comment by Dinesh2019** [comment]
- [x] NCD risk factors: Proportion and scoring --- data mismatch We have the data mismatch between number in the jasper report and the Excel

- [x] Cancer warning signs - Female

- [x]  Cancer warning signs - General

- [x] Self care practices in Hypertension

- [x] Self care practices in Diabetes

- [x] Blood glucose levels in Diabetic patients

- [x] Antenatal and postnatal cases

- [x] Use of social security schemes

- [x] Fever survey details 

- [x] Line list of children under age of 5 (Acute diarheal disease, Acute respiratory infection) --- data mismatch and one column is missing

- [x] Line list of children with immunisation status --- data mismatch total count as 717 in new and in old is 713

- [x] Line list of individual with diabetes

- [x] Line list of individual with hypertension

- [x] Line list of individual with NCD factor

Above which not marked are QA Failed

**Comment by Gojo-Taqi** [comment]
For this report, Line list of individual with NCD factor, there is data missmatch for 3 cells, I am not able to debug why that's happening. Will need to pair on that issue with someone.
For the report - Use of social security schemes, not able to get the old reports data as it takes forever to run.

**Comment by sachsk** [comment]
- Line list of children under age of 5 (Acute diarheal disease, Acute respiratory infection) in this report column "Child fully immunized till date" is not added as this filed the voided.
-  Line list of children with immunisation status in this report data are mismatched due to in old report void check is not present.

**Comment by Dinesh2019** [comment]
- [x] NCD risk factors: Proportion and scoring  we have data mismatch for this two field 

Individuals undertaking physical activity > 150 minutes/week - old report data 736 and new report data 735
Individuals having family history of high BP, DM and heart disease - old report data 189 and new report data 188

- [x]  Line list of individuals with diabetes under Head Of Household for this two individual Geetha S and Parameshwar T Head Of Household name are mismatched between old and new report 
- [x]  Line list of children under age of 5 -  Household number data is mismatched for Sathvik S user we have the head of house hold in the old report Sunil Sunil and new report Bharathi S, Influenza like illness - we have data mismatch eg : Aksarakhatun Azharuddin for Influenza we have No in old report and we have the blank space in new report
- [x]  Linelist of children with immunization status - total data is mismatched we have old report 708 and in new report 706 

- [x]  Antenatal and postnatal cases - Antenatal Linelist - for Individual Naseema M -  Head of household in old report is yes but in new report it is No 
- [x]  Blood glucose levels in Diabetic patients Line list - for Ganesh Churya the head of household in new report - Someshwara and in old report - Ganesh Churya
- [x]  Cancer warning signs - general - Linelist - we have the count mismatch between old and new report in old report the total count is 2290 and new report Is 2284
- [x]  NCD risk factors : proportion and scoring - Linelist - we have the count mismatch in new report 2291 and in old report 2290
- [x]  Self care practices in Diabetes Mellitus - head of household data is mismatched between old and report for these individuals Parameshwar T and Ganesh Churya

**Comment by BEULAHEVANJALIN** [comment]
> -  Line list of children under age of 5 - Household number data is mismatched for Sathvik S user we have the head of house hold in the old report Sunil Sunil and new report Bharathi S, Influenza like illness - we have data mismatch eg : Aksarakhatun Azharuddin for Influenza we have No in old report and we have the blank space in new report

Since there are two head of the householders exist, there is a name mismatch between the old and the new report

**Test Query:**
```
select i.id,
       i.first_name,
       i.last_name,
       extract(year from age(i.date_of_birth)),
       h.id house_id,
       r.role
from individual i
         inner join group_subject gs on gs.member_subject_id = i.id
         inner join household h on h.id = group_subject_id
         inner join group_role r on r.id = gs.group_role_id
where h.first_name like 'Sunil';
```
![image.png](https://images.zenhubusercontent.com/6391ce979fce9d1191f3aaac/1a854531-51cf-4434-9ff8-7683b0149f1a)

**Comment by BEULAHEVANJALIN** [comment]
>  Line list of individuals with diabetes under Head Of Household for this two individual Geetha S and Parameshwar T Head Of Household name are mismatched between old and new report


```
select i.id,
       i.first_name,
       i.last_name,
       extract(year from age(i.date_of_birth)),
       h.id house_id,
       r.role
from individual i
         join group_subject gs on gs.member_subject_id = i.id
         join yenepoya.household h on h.id = group_subject_id
         join group_role r on r.id = gs.group_role_id
where h.id = (
    select i.id
    from public.individual i
    where i.id = (select group_subject.group_subject_id
    from yenepoya.individual
    join group_subject on individual.id = group_subject.member_subject_id
    where first_name = 'Geetha'
  and last_name = 'S'));
```
![image.png](https://images.zenhubusercontent.com/6391ce979fce9d1191f3aaac/1718a2a7-4503-4026-80c3-aa0e1bff148e)


```
select i.id,
       i.first_name,
       i.last_name,
       extract(year from age(i.date_of_birth)),
       h.id house_id,
       r.role
from individual i
         join group_subject gs on gs.member_subject_id = i.id
         join yenepoya.household h on h.id = group_subject_id
         join group_role r on r.id = gs.group_role_id
where h.first_name = 'Parameshwar';
```
![image.png](https://images.zenhubusercontent.com/6391ce979fce9d1191f3aaac/1e5025cf-b247-4076-9d21-7caa144d8673)

**Comment by BEULAHEVANJALIN** [comment]
```
set role yenepoya;
select concat(i.first_name, ' ', i.last_name) as head_of_household_name,
       i.is_voided,
       h.id                                      house_id,
       gs.is_voided,
       r.role
from yenepoya.individual i
         inner join group_subject gs on gs.member_subject_id = i.id
         inner join yenepoya.household h on h.id = group_subject_id
         inner join group_role r on r.id = gs.group_role_id
where i.first_name = 'Naseema'
  and i.last_name = 'M';
```

![image.png](https://images.zenhubusercontent.com/6391ce979fce9d1191f3aaac/3a2276d0-bbdb-4f95-a70b-ac4d4fbdca37)

**Comment by Dinesh2019** [comment]
For Blood glucose levels in Diabetic patients Line list and NCD risk factors : proportion and scoring we are getting the below error

![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/73987bcf-c411-4557-b000-60db66bed6d4)
