### ISSUE TITLE
[ETL REPORT] Graph reports

### ISSUE THREAD

**Issue by sachsk** [avniproject/yenepoya#142]
Save these reports in the Yenepoya ETL directory
Update the query here : https://docs.google.com/spreadsheets/d/15U3mOkcVjHhXlr318uj8DRQNzC6mBOTf-GEPf9SLfTM/edit#gid=693027088

- [x] Children Age groups
- [x] Population map

**Comment by Dinesh2019** [comment]
- [x] Children Age groups - graphs and linelist data is mismatch

Graph image
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/2f271307-02ab-4fac-94a2-066ff5150346)

Linelist data :
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/81d4d274-b1ad-40cc-9a8e-3a22e15bbc77)
