### ISSUE TITLE
[ETL REPORT] Independent linelist

### ISSUE THREAD

**Issue by sachsk** [avniproject/yenepoya#143]
Save these reports in the Yenepoya ETL directory
Update the query here : https://docs.google.com/spreadsheets/d/15U3mOkcVjHhXlr318uj8DRQNzC6mBOTf-GEPf9SLfTM/edit#gid=693027088

- [x] Eligible couple - line list
- [x] Linelist for antenatal women
- [x] Line list of postnatal women
- [x] Linelist of women with abortion

**Comment by Gojo-Taqi** [comment]
The report Eligible couple - line list, was not tested because the report is not able to get any data

**Comment by Dinesh2019** [comment]
Getting this error 
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/c557d908-1b25-414e-a1a0-3fa1ef115225)
Getting errors while executing the old qwery need to connect with taqi

**Comment by Dinesh2019** [comment]
Getting below error while trying to run the old qwery
for Linelist for antenatal women
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/e93ae037-59f8-4a24-8a6a-bc344ae17f2a)

for  Line list of postnatal women
![image.png](https://images.zenhubusercontent.com/640ef9e3ad2fcf337b550a3f/afb1e4ca-bff8-4d28-94fc-1f4869fb462f)
