### ISSUE TITLE
[Yenepoya Support] Create request json for new longitudinal export

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/yenepoya#148]
**Support ticket** - https://avni.freshdesk.com/a/tickets/3070

We have the readme updated with one sample request json already, update it with the fields mentioned in the following link https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=1110739736

**Note for devs** - Fields in the sheet are highlighted according to respective forms, it covers mostly all the fields in any form, so better use a query to get all those concepts uuids. 

Link to the request Json -
https://github.com/avniproject/yenepoya/blob/master/New%20longitudinal%20request.json

**Comment by nupoorkhandelwal** [comment]
Awaiting a reply from client for a clear detailed list.

**Comment by nupoorkhandelwal** [comment]
Readme - https://avni.readme.io/docs/new-longitudinal-export

Bug card for Delivery encounter -https://github.com/avniproject/avni-webapp/issues/1056

**Comment by Dinesh2019** [comment]
While trying to exceute the below json it is getting failed 

{
  "individual": {
    "uuid": "d22027ff-e019-4d1c-9352-bd740efccc38",
    "fields": [],
    "filters": {
      "addressLevelIds": [],
      "date": {
        "from": "2023-01-12",
        "to": "2023-05-04"
      }
    },
    "programs": [
      {
        "uuid": "00c6dfe3-109c-4099-8550-89a457e9c176",
        "fields": [
        ]
      }
    ],
    "encounters": [
      {
        "uuid": "ef79eb31-2d19-441d-bb21-0838ceaed958",
        "fields": [],
        "filters": {
          "includeVoided": true
        }
      }
    ]
  },
  "timezone": "Asia/Calcutta"
}

https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMFlWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fe41274471a8f59b425385e8deb275df56fe6666/Screenshot%202023-10-08%20at%204.35.34%E2%80%AFPM.png

**Comment by Dinesh2019** [comment]
Created the bug card for the fields returns all the data for individual,programs

https://github.com/avniproject/avni-webapp/issues/1057

**Comment by nupoorkhandelwal** [comment]
{
  "individual": {
    "uuid": "d22027ff-e019-4d1c-9352-bd740efccc38",
    "fields": [],
    "filters": {
      "addressLevelIds": [],
      "date": {
        "from": "2023-01-12",
        "to": "2023-05-04"
      }
    },
    "programs": [
      {
        "uuid": "00c6dfe3-109c-4099-8550-89a457e9c176",
        "fields": [
        ],
        "encounters": [
          {
            "uuid": "ef79eb31-2d19-441d-bb21-0838ceaed958",
            "fields": [],
            "filters": {
              "includeVoided": true
            }
          }
        ]
      }
    ]

  },
  "timezone": "Asia/Calcutta"
}
