### ISSUE TITLE
Write script to update NCD risk score of all individuals

### ISSUE THREAD

**Issue by Gojo-Taqi** [avniproject/yenepoya#153]
Link to the ticket 
- https://avni.freshdesk.com/a/tickets/3684
- https://avni.freshdesk.com/a/tickets/4021

During the initial development of the app, the decision rule was adding scores that do not even are correct.

The following are the tasks that need to be done- 
- [x] Update the Decision rule in the NCD enrolment form. (30 mins)
- [x] Update the Decision rule in the NCD follow-up form. (30 mins)
- [x] Write a script that updates the Risk score values of all those individuals who are enrolled in this program, (2 hours)
```
This is the existing logic - 
totalScore = smokingScore + alcoholScore + ageScore + waistCirumferenceScore + physicalActivityScore + familyHistoryScore + littleInterestScore + feelingDownDepressedScore;

```
This will again be 2 separate update scripts, one will update in enrolment, and the other will update in program_encounter.
i. update program_enrolment, 
set "risk score" = existing_value - ('Feeling  down, depressed or hopeless' + 'Little interest or pleasure in doing things')
ii. update program_encounter, 
set "risk score" = existing_value - ('Feeling  down, depressed or hopeless' + 'Little interest or pleasure in doing things')

---------------------------------

For the second ticket, update the encounter eligibility rule.
Current rule
```
'use strict';
({params, imports}) => {
  const individual = params.entity;
  const consent=individual.getObservationReadableValue('Respondent agrees to consent');
  return  _.isEqual(consent,'Yes');
};
```
​
- [x] Update the rule such that the "Household survey" encounter should **not** come in the '**New form visit**' or in the **unplanned visits section**.

**Comment by BEULAHEVANJALIN** [comment]
Bundle before doing any changes:

[Yenepoya.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2puQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ea851c16620a4878b770735910ad1c2cc1eec138/Yenepoya.zip)
[Yenepoya UAT.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM25uQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2985344e55ccb5695e2587d7945579fa7c97f951/Yenepoya%20UAT.zip)

uploaded prod bundle to UAT on 16/05/2024

**Comment by Gojo-Taqi** [comment]
@BEULAHEVANJALIN I updated the card, can you take a look.

**Comment by Gojo-Taqi** [comment]
Since Beulah is on leave today, moving this card back to Support ready.

**Comment by BEULAHEVANJALIN** [comment]
Seems the data has many inconsistencies, and even the current total scores don't match the current risk values. I don't know why this has been like this for so long. Instead of fixing the incorrect data, it's better to write a query to calculate the risk score and store it in the appropriate column.

https://gist.github.com/BEULAHEVANJALIN/cc908f17211547d14dc4992d2972087a

[inconsistent_data.csv.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXZ6QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--635d3532e03720eb68ad9c6ca53ff2fc8cf94d2e/inconsistent_data.csv.zip)

**Comment by BEULAHEVANJALIN** [comment]
Waiting for the script to be reviewed.

https://avni.freshdesk.com/a/tickets/4046

**Comment by BEULAHEVANJALIN** [comment]
Have executed the query in the UAT for both the enrolment and encounter tables on 21/05/2024. Moving this to QA before making any changes in the prod.

**Comment by Gojo-Taqi** [comment]
<img width="400" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmIvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--881865eac1d65c1c30ee0349504c7afe2a6cb50d/1716361677817.JPEG" alt="1716361677817.JPEG" />

From the screenshot, for this individual, according to the requirement, the risk score should be 5.
But it is calculating it to 3.

Alcohol consumption - yes (1)
Waist circumference - 89 (1)
Physical activity - No (1)
Family history - Yes (2)

Total risk score = 1+1+1+2 = 5.
@BEULAHEVANJALIN can you take a look

**Comment by Gojo-Taqi** [comment]
Got an error on uploading uat bundle to prod.
On investigating, turns out the form_mapping uuid's for both the orgs are different.

Instead of fixing them, easy solution is to create a new UAT org and live happily.
