### ISSUE TITLE
[Yenepoya] Cancel form Household and Individual

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#16]
https://docs.google.com/spreadsheets/d/1oXXGqTgumvIW7EItRRKDLQmgPT4B2iU5wpwdZxy66GQ/edit#gid=224891254

- Please check there are different form for survey cancel and Fever survey cancel.

**Comment by garimadosar5** [comment]
QA Notes - 

- Cancellation date is not auto-filled. (for both individual and household)
- Form is crashing on NEXT button. (For Individual) - DONE
![Screen Shot 2020-04-15 at 4.26.13 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/9caaf752-3bd3-4a8e-8057-4d7ffa0304ef)

**Comment by sachsk** [comment]
@garimadosar5  we cant add the auto-filled date in cancel form

@sachsk it is same as in any other encounter. I guess in Cancellation form we do not show the cancel/encounter date in the form. Just confirm this.

@garimadosar5 yes we have not shown cancel date in cancel form
@garimadosar5 removed cancel date

**Comment by garimadosar5** [comment]
QA Notes 2-
- when I am cancelling the visit, it should schedule the next visit to next year. It is scheduling the next visit in the same year.
![Screen Shot 2020-04-19 at 9.01.05 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/08e2f610-e5e2-4e77-99f7-d5ccd6f345bc)
