### ISSUE TITLE
[Yenepoya] Mother PNC followup form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#22]
https://docs.google.com/spreadsheets/d/1oXXGqTgumvIW7EItRRKDLQmgPT4B2iU5wpwdZxy66GQ/edit#gid=394954716

**Comment by garimadosar5** [comment]
Rules' Estimate - 1 Hr.

**Comment by garimadosar5** [comment]
QA Notes - 
- For question "Health status of the newborn", This should give this message "Normal cannot be selected with other"
![Screen Shot 2020-07-06 at 7.46.15 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/acf24fee-8e29-47bc-8de8-7bf1cdf39a4a)
- Question "Practicing exclusive breastfeeding" is missing.
- High blood pressure is always in the recommendation table and other abnormalities are not showing in recommendation table. (Health status of new born)
Case - Renu bansal.

**Comment by sachsk** [comment]
point 1 will be fixed through the translation(when we upload translation)
- @sachsk This is English text, how are we supposed to do that? when will we upload the translation?
