### ISSUE TITLE
[Yenepoya][Report] Individual Education and Occupation

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#29]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=0

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (except multi-select type questions).

**QA CHECKLIST**
- [ ] percentage Calculation
- [ ] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are as mentioned in requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by nupoorkhandelwal** [comment]
@sachsk As per the requirements mentioned in the card,  coded values should also be displayed even if its number/count is 0. Rest is working completely fine

**Comment by nupoorkhandelwal** [comment]
@sachsk https://reporting.openchs.org/question/766

In this report one of the Occupational status, "Categories" field is empty.
