### ISSUE TITLE
[Yenepoya][Report] NCD risk factors: Proportion and scoring

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#33]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=1465272386

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (except multi-select type questions).

**QA CHECKLIST**
- [ ] percentage Calculation
- [ ] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are as mentioned in requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by vindeolal** [comment]
We have split Registration related report and NCD followup report.
NCD age groups.
NCD risk factors: Proportion and scoring.

**Comment by garimadosar5** [comment]
QA Notes - 
Report - NCD: Score and proportion.
- For BMI, Total % is not matching to 100%. BMI is mandatory for all cases.
- Line List - Risk score is coming null. If a person is enrolled in NCD, the risk score cannot be null.

**Comment by vindeolal** [comment]
- Fixed
- Most of the individuals have not done any followup visits. You can confirm this by clicking on individual and checking their observations in the latest completed visit.
