### ISSUE TITLE
[Yenepoya Report] Household - Socio demographic Profile (Individual and Household Reg)

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#34]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=1725226428

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (except multi-select type questions).

**Comment by garimadosar5** [comment]
QA Notes - 
- Change the column name "Label" to "Demographic Profile".
- Indicator "Total Population", Percentage should be NULL or NA or leave it empty. Remove 0.00%
- In other reports, we are calculation % in decimal. In this, we are not. Remove (.00) after number or put decimal number also.
- % calculation of last indicator "Families with BPL ration card" is wrong. Total HHs are 10 so (4/10*100= 40%). 
- Indicator "Number of eligible couples" calculation is wrong. There are a total of 2-3 married women registered in the system.

**Comment by vindeolal** [comment]
- Done
- Done
- Done
- Done
- "Number of eligible couples" is Total married women Age between 15-49. Also, their Marital status is taken from the latest individual survey.
