### ISSUE TITLE
[Yenepoya] Cancel form for Pregnancy and Child Program

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#41]
https://docs.google.com/spreadsheets/d/1oXXGqTgumvIW7EItRRKDLQmgPT4B2iU5wpwdZxy66GQ/edit#gid=224891254

- Pregnancy
- Child

**Comment by garimadosar5** [comment]
Estimate - 30 mins

**Comment by vindeolal** [comment]
@garimadosar5 I see that this is done. We already have cancel form for all the visits and skip logic is also there in the form. Caan you please confirm this.
