### ISSUE TITLE
[Yenepoya][Report] Details of program enrolment

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#49]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=214833381

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (except multi-select type questions).

**QA CHECKLIST**
- [ ] percentage Calculation
- [ ] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are as mentioned in requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by vindeolal** [comment]
Working on SR prod issue, so moving this card on hold

**Comment by garimadosar5** [comment]
QA Notes - 
- Total antenatal mother enrolled is showing 128.57%, is it because there are some cases enrolled in pregnancy but not an eligible couple? Please check once.
- Following are the indicators not calculated properly. these enrolled numbers are showing for MAY 20 also but all the enrollments are after June or July.
1. Total antenatal mothers enrolled	
2. Total postnatal mothers registered
3. Total under-five children enrolled
4. Total individuals with Hypertension
5. Total individuals with Diabetes
6. Total individuals registered under NCD risk factor category
