### ISSUE TITLE
[Yenepoya][Report] Map Report

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#50]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=0

**QA CHECKLIST**

- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are as mentioned in requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by vindeolal** [comment]
For testing map reports you need to have a registration location for the registered household. You can turn on your location from Genymotion and give some values there in the coordinates, or after registering the household you can use ```update_registration_location_for_id(household_id, latitude, longitude)``` function to insert some random location for a household. This function will only work for ```yenepoya_uat``` User, and is just for testing.
example,
```select update_registration_location_for_id(138361, 12.810513, 74.880121);```

**Comment by garimadosar5** [comment]
QA Notes - 
- What happens if the household location is different and form filled (fever form, diabetes enrolment etc.) at a different location.
- What if household location changes in the survey form.

**Comment by vindeolal** [comment]
@garimadosar5 
We take the location as per the household registration form. So we don't care where other forms are filled.
Also as long as no changes are made in the household registration location will remain same, no matter what location is filled in survey form.
