### ISSUE TITLE
[Yenepoya][Report] Individual Report - Influenza Like Illness Report

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#51]
Ref Doc - https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=214833381

- Report and Line List

**Comment by garimadosar5** [comment]
QA Notes - 
- In other reports, we are showing columns name differently. (within the table and little bigger font.)
- check for % calculation related to Individual survey. the denominator should be a total individual registered. It seems it is calculating total individual with Individual surveys.
- Delete duplicate report - 
https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2Fyenepoya%2FReports%2FAggregates&reportUnit=%2Fyenepoya%2FReports%2FAggregates%2FInfluenza_Like_Illness_in_last_6_weeks&standAlone=true

**Comment by vindeolal** [comment]
- Fixed the styling
- Fixed % calculation
- Deleted extra report
