### ISSUE TITLE
[Yenepoya Report] Line list of eligible couple

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#52]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=173136506

**QA CHECKLIST**

- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are as mentioned in requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by garimadosar5** [comment]
QA Notes - 
1. Filter age group - Last filter - "31 - 49". (currently, 30 years is coming in both 25-30 and 30 - 49).

**Comment by vindeolal** [comment]
Fixed
