### ISSUE TITLE
[Yenepoya Report] Household - Socio demographic Profile (Individual and Household Survey)

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#54]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=1725226428

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (except multi-select type questions).

**QA CHECKLIST**
- [x] percentage Calculation
- [x] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [x] Line List - Check for all the columns
- [x] Line List - Column names are as mentioned in requirement sheet.
- [x] Individual and Household cases are pointed to UAT.

**Comment by garimadosar5** [comment]
QA Notes - 
- Line List - Add "Name of Household" and "Household Number" in all the household related lists. - **DONE**
-  % calculation does not seem right. Total households register are 10. for "Households availing Social Security Schemes", % should be 20%. Check once. - **DONE**
- % calculation for indicator - "Individuals with flu-like symptoms" - (12/31*100 = 38.7). In the report, it is showing 57.14%. Check once. - **DONE**
- Also, the aggregate report show 4 and when I click on the number it shows only 2 individuals. - **DONE**
- Check count for indicator - "Individuals who are married" - I counted 3 individuals.  - **DONE**

-  % calculation for indicator - "Individuals who are married" - (47/151*100 = 31.125%). In the report, it is showing 30.72%.  - **DONE**

**Comment by vindeolal** [comment]
- done
- done
- done
- done
- done
- It is taken from the latest individual survey. done
