### ISSUE TITLE
[Yenepoya Report] Household social class and mother tongue

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#55]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=1725226428

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (except multi-select type questions).

**QA CHECKLIST**
- [ ] percentage Calculation
- [ ] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are as mentioned in requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by sachsk** [comment]
- [x] aggregates report

- [x] line list report

- [x] filters

- [x] linking aggregates with Linelist

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Columns 'HH number' and 'Village' are missing fro line list

**Comment by hithacker** [comment]
@garimadosar5 Added those columns
