### ISSUE TITLE
[Yenepoya Report] Household - Health Seeking Behaviour

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#57]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=1725226428

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (except multi-select type questions).

**QA CHECKLIST**
- [x] percentage Calculation
- [x] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [x] Line List - Check for all the columns
- [x] Line List - Column names are as mentioned in requirement sheet.
- [x] Individual and Household cases are pointed to UAT.
Report :
https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2Fyenepoya%2FReports%2FAggregates&reportUnit=%2Fyenepoya%2FReports%2FAggregates%2FHealth_Seeking_Behaviour&standAlone=true

**Comment by garimadosar5** [comment]
QA Notes -
- % calculation is wrong.  - **DONE**
- Move this to UAT. (Line list and data entry app). - **DONE**
- Household Number column is missing. - **DONE**
- Column Name - "Panchayat", Rename it as "Panchayat/Ward" and "Village" as "Village/Ward". Because in the case of urban there is no panchayat or village. - **DONE**
-  "Acute Illness" <- "no health care" - "Name of facility" should not there because for no health care there will not be any facility. - **DONE**
- Regarding the previous point, do not remove "no health care" from the column "Type of facility". But it should have only one row and in column "Name of facility" value should be "NA". - **DONE**
- Line List is not showing right cases. for eg: Acute illness <-Government type facility <- YMNCH, Number is one in the report but in the line list two cases are showing.  - **DONE**

**Comment by vindeolal** [comment]
Fixed last two points.
