### ISSUE TITLE
[Yenepoya] [Report]  Fever survey details

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#60]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=138535066

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (except multi-select type questions).

**QA CHECKLIST**
- [ ] percentage Calculation
- [ ] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are as mentioned in requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by garimadosar5** [comment]
QA Notes - 
- "History if fever in last 15 days". Line list shows 8 cases only. In Aggregate it shows 9. - **DONE**
- "Individuals with history of fever where provided with LLIN by Govt. health workers", Aggregate shows 7 but in LL there are 8 cases. - **DONE**
- Gender filter is missing.

**Comment by hithacker** [comment]
@garimadosar5 Issues are fixed.

**Comment by hithacker** [comment]
@garimadosar5 Added gender filter.
