### ISSUE TITLE
[Yenepoya][Report] Blood Pressure measurement in Hypertensives

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#62]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=798194163

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (except multi-select type questions).

**QA CHECKLIST**
- [ ] percentage Calculation
- [ ] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are as mentioned in requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by garimadosar5** [comment]
QA Notes - 
- All Systolic(s.no. 1 - 6) should be equal to all diastolic (7-12). - **DONE**
- Line list has more number of cases than in the aggregate report. - **DONE**
- Total Hypertensive enrolments are 71 and in the report, the total is67 (first 6 indicators).  - **DONE**
- Total % of all systolic should be 100% (first 6 indicators).  - **DONE**
- Line List - the last column should be "who believe their blood pressure is under control". right now it says. blood sugar. and also the text is not complete.

**Comment by sachsk** [comment]
added hyperlinks that point to data entry app in line list 
fixed column name
