### ISSUE TITLE
[Yenepoya][Report] Line List Of Postnatal Women

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#65]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=173136506

**QA CHECKLIST**
- [x] Line List - Check for all the columns
- [x] Line List - Column names are as mentioned in requirement sheet.
- [x] Individual and Household cases are pointed to UAT.

**Comment by vindeolal** [comment]
- This LL is where the outcome reported is delivery (other than ```Abortion (spontaneous)```). Right now report shows abortion cases also. **updated**
Mentioned in the requirements (Line list of women who are in the pregnancy program and delivery is reported in the selected time period.)
- Date filter should be on ```Date of Pregnancy Outcome``` and not when the outcome encounter was filled.**Updated**
- Change column name ```Village``` to ```Village/ward/census town```. **updated**
- Column ```Head of Household``` should display the name of the head of the household. **fixed**
- ```Date of Delivery``` column is missing from the report. **added**
