### ISSUE TITLE
[Yenepoya][Report] Line List of women with Abortion

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#66]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=173136506

**QA CHECKLIST**
- [x] Line List - Check for all the columns
- [x] Line List - Column names are as mentioned in requirement sheet.
- [x] Individual and Household cases are pointed to UAT.

**Comment by vindeolal** [comment]
- Rename column ```Village``` to ```Village/ward/census town``` as mentioned in the report requirements.
- Column ```Head of Household``` should display the name of the head of household, use ```yenepoya_member_household_view``` for this.
- Re-arrange the Address filter as per the address hierarchy Surveillance unit -> Panchayat ->Village.
- Column names ```Received & consumed supplementary nutrition``` and ```Calcium Received and Consmed``` are trimmed.
- I'll be good if we open the data-entry app in a new tab as we do for other reports. You can pass ```hyperlinkTarget="Blank"``` prop to the```TextField``` for this.
