### ISSUE TITLE
[Yenepoya][Report] Line List of children with immunisation status

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#68]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=173136506

**QA CHECKLIST**
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are as mentioned in requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by vindeolal** [comment]
- Add title of the report.
- ```Vaccine Status``` filter is missing.
- Rename ```Village``` column to ```Village/ward/census town``` as mentioned in the report.
- Column ```Head of household``` is name of the head of household, use ```yenepoya_member_household_view``` for this.
- Remove dot(.) from ```Age in months``` column.
