### ISSUE TITLE
[Yenepoya][Report] Line list of individual with diabetes

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#69]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=173136506

**QA Checklist**
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are as mentioned in the requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by garimadosar5** [comment]
QA Notes -
- Move report to UAT - **DONE**
- Age should not be in Decimal. - **DONE**
- Remove time from DOB. - **DONE**
- Rename Column "Village" to "Village/Ward/Census town". - **DONE**
- Column "Head of Household" should have the name of head of the household. - **DONE**
- Column text is incomplete for some columns - **DONE**
- Add age filter. - **DONE**

**Comment by garimadosar5** [comment]
QA Notes - 2
- Move report to UAT.
- Add age filter.

**Comment by garimadosar5** [comment]
QA Notes - 2
- There are 63 cases but in report, it shows only one case. - **DONE**
- In Household number and HH Head name column if the value is not there, it should show NULL. In other reports we are doing the same. - **DONE**
- Age filter is not working.  -**DONE**


- Gender filter is missing.

**Comment by hithacker** [comment]
@garimadosar5 Added Gender filter
