### ISSUE TITLE
[Yenepoya][Report] Line list of individual with hypertension

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#70]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=173136506

**QA CHECKLIST**
- [x] Line List - Check for all the columns
- [x] Line List - Column names are as mentioned in requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by garimadosar5** [comment]
QA Notes - 
- Some columns do not have complete text. for eg: "What about your". (Check all the columns).
- on 4th page, one case goes from 3rd to 4th page.
 ![Screen Shot 2020-07-01 at 9.36.45 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/7b21f6ab-7df1-4759-96e1-083211a373fe)

**Comment by sachsk** [comment]
fixed style
added hyperlinks that point to the data entry app.
