### ISSUE TITLE
[Yenepoya][Report] Post natal cases - followup

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#73]
https://docs.google.com/spreadsheets/d/1yeUky6eZKLEBl89gj0UabxAMMsnpGUBHUNxolxDLYnE/edit#gid=1001045666

For all aggregate reports please note that following patterns are to be followed
1. Coded answers with 0 values should also appear
2. One of the indicators should be "Not responded", so that the tally matches
3. There should be total displayed where it shows the total count and total percentage tallying to 100% (Except in case of Multi-select question)

**QA CHECKLIST**
- [ ] percentage Calculation
- [ ] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are as mentioned in requirement sheet.
- [ ] Individual and Household cases are pointed to UAT.

**Comment by vindeolal** [comment]
@garimadosar5 @nupoorkhandelwal 
Question
- This report will not include/show the unplanned PNC visits, Is this the desired behavior?
@nupoorkhandelwal I think you can change this condition 
```where no_of_visits >= 2 and encounter_name = 'PNC 1'``` 
to 
```where no_of_visits >= 2 and visit_number=1``` 
and same for other cases also
**As discussed with Garima, there wont be any unplanned visit, so keeping the checks as it is for PNC 1 and PNC 2** 

**Line List report**
- Rename the columns ```Panchayat``` and ```Village``` to  ```Panchayat/Ward``` and ```Village/Ward``` as given in the requirements. **updated**
- ```Name of PHC/UPHC``` and ```Date of Delivery``` columns are missing from the report. **added**
-  ```Head of Household``` is the name of the head of household and not whether the person is head of household or not, use ```yenepoya_member_household_view``` for this. **updated**
