### ISSUE TITLE
[Yenepoya][Report] UAT feedback for Reports.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#78]
https://docs.google.com/document/d/137iq-PVtmxSZnZJqxOjFs7BfVE3j8W8m/edit

1.  Sort the categories by options. Keep Other, No, None etc. at the end of list.
Reports - 
* Health Seeking Behaviour
* Household Social Class and Mother tongue
* Individual Education and Occupation - (Also for education Sort it in ascending order like - Illeterate, Primary, secondary and so on).
* Self-reported morbidity among family members	
* Use of social security schemes	

2.  **Report Environmental Factors** - 
Put these two indicators together - "Households NOT using any domestic purification methods for drinking water" and "Households with well water as a source of water for
drinking purposes".

3. Filters are missing in the report - "Self care practices in Hypertension". **Done**

4. Use Sentence case for each indicator in reports.
Report - 
*** Individual Socio-Demographic Report -** 
- “Total population”
- Spacing issues in case of “Total population 0-5 years”.
*** Blood Pressure measurement in Hypertensives** - 
- Hypertensives with optimal Diastolic blood pressure	
- Hypertensives with normal Diastolic blood pressure
- Hypertensives with high normal Diastolic blood pressure	
- Hypertensives with grade 1 Diastolic blood pressure
- Hypertensives with grade 2 Diastolic blood pressure
- Hypertensives with grade 3 Diastolic blood pressure
*** Fever Survey details -**    **Done**
- With History of fever in last 15 days
- Individuals with history of fever visited by Any Govt. health worker/MPW  in past 3 months
- Individuals with history of fever who are aware of any mosquito control measures undertaken by the Govt. health worker other than the LLIN ( examples)? - Remove "?"
*** Influenza like illness in last 6 weeks -** 
- Individuals having fever, cough and Myalgia
*** Household Socio demographic profile -** 
- Households availing Social Security Schemes
*** Selfcare practices in Diabetes Mellitus**	                                   **Done**
- Alcohol use in last 1 year - No Alcohol use
- Alcohol use in last 1 year - Not responded
- Tobacco use - Never user	
- Tobacco use - Used previously in last visit and now stopped
- Tobacco use - Started new after last visit	
- Tobacco use - Reduced using tobacco compared to last
- Tobacco use - Continuing same	
*** Self care practices in Hypertension**	                                     **Done**
- Alcohol use in last 1 year - No Alcohol use	
- Alcohol use in last 1 year - Not responded	
- Tobacco use - Never user	
- Tobacco use - Used previously in last visit and now stopped
- Tobacco use - Started new after last visit
- Tobacco use - Reduced using tobacco compared to last visit		
- Tobacco use - Continuing same

5. Report - "Self reported morbidity among family members" **Done**
- In Categories, some categories are in small letters. that needs to be changed in-app. Please fix that.

**Comment by vindeolal** [comment]
@nupoorkhandelwal fixed Self reported morbidity report answer orders. Moving card to QA ready.

**Comment by garimadosar5** [comment]
QA Notes - 
- Self-reported morbidity among family members - In this report Option 'No' should be at the end of respective categories.
