### ISSUE TITLE
[Yenepoya] Add enrolment eligibility criteria in program.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#82]
- If an individual is not part of familiy it should not allow to enrol in any of the program.
- Put checks in pregnancy and child program.
For Pregnancy Program - 
- Female, Age between 15 and 49.
For Child Program - 
- Age between 0-5 years.

### Tech Task

- [x] Add age and gender check in pregnancy program
- [x] Add age check in Child program
- [x] Add "individual is not part of familiy it should not allow to enrol in any of the program" check in all Programs
- [x] Change the RuleEvaluationService

**Comment by garimadosar5** [comment]
QA Notes - 
- first point is not done. 
Case - Test Fix

**Comment by vindeolal** [comment]
Added rule for checking the household. User below staging APK to test
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/staging-apks/staging-553fe-2020-08-10-17-40-18.apk

**Comment by garimadosar5** [comment]
QA Notes - 
- The individuals that are linked to the household, not able to enrol in the program.
- Also, in individual profile it is not showing that the case is linked to any household.
Case - Ramendra Jayant
- Rule failure.
 ![Screen Shot 2020-08-10 at 8.11.25 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/f388f0b3-e9e8-4fbe-8051-88345d2653b0)

**Comment by vindeolal** [comment]
@garimadosar5 on staging rules were not deployed. Did that now.

**Comment by garimadosar5** [comment]
QA Notes - 
- Male can be enrolled into a program. (anyone can be enrolled into pregnancy program)
- Even if individual is linked to household, it gives the message "Link individual to household". (This is not related to this card. Let me know if there is a lot of work, will create a new card.)
![Screen Shot 2020-08-11 at 11.23.43 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/ff6ff7b7-d49e-4ec9-b28c-4ad29961058f)

**Comment by garimadosar5** [comment]
QA Notes - 
- No progrm is showing for this case. 
![Screen Shot 2020-08-14 at 1.35.55 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/9252f5cc-ed3b-48cd-9f7d-e0ba08b7cf9c)

- Even if individual is linked to household, it gives the message "Link individual to household". (This is not related to this card. Let me know if there is a lot of work, will create a new card.) **This is also not done**

**Comment by sachsk** [comment]
@garimadosar5 
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prod-apks/prod-x86-4ba3d-2020-08-21-09-38-26.apk
Use these APK for testing
