### ISSUE TITLE
[Yenepoya] UAT feedback for MCH for app 

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/yenepoya#87]
https://docs.google.com/spreadsheets/d/1gbEK3KCA9LN9HayFqBh66XCJxKiy3C_AUoNlF8topGU/edit#gid=0

feedbacks from Row 42.

**Comment by garimadosar5** [comment]
QA Notes- 
- Individual survey form - Not able to select any option.
still not working from HEALTH STATUS page.
- Household survey form - Row 40,41 and 44,45. add skip. - **DONE**
- Comment - Row 52 is not done. - **DONE**
- Rule failure telemetry - 
![Screen Shot 2020-09-08 at 3.36.45 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/7a03cf26-0642-4080-b960-a05ef9b6bf8a)

**Comment by sachsk** [comment]
Please use these APK for testing
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prod-apks/prod-x86-57187-2020-09-11-09-46-58.apk

**Comment by garimadosar5** [comment]
![Screen Shot 2020-09-14 at 12.17.49 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/f53772d9-ad8b-4f65-b066-f2357a2d8cbf)

**Comment by sachsk** [comment]
https://s3.ap-south-1.amazonaws.com/samanvay/openchs/prod-apks/prod-x86-57187-2020-09-14-12-32-10.apk
